steps:
  - id: 'Build Docker Image'
    name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '--tag', 'us-central1-docker.pkg.dev/oval-crawler-444615-k3/medical-apiscore/msa-smart-triage-img:$COMMIT_SHA',
        '-f', './deploy/Dockerfile',
        '.'  # contexto desde raíz, para incluir app/, main.py, requirements.txt, etc.
      ]

  - id: 'Push Docker Image'
    name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/oval-crawler-444615-k3/medical-apiscore/msa-smart-triage-img:$COMMIT_SHA'
      ]

  - id: 'Deploy to Cloud Run'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'flask-app-service',
        '--image', 'us-central1-docker.pkg.dev/oval-crawler-444615-k3/medical-apiscore/msa-smart-triage-img:$COMMIT_SHA',
        '--port', '3333',
        '--platform', 'managed',
        '--region', 'us-central1',
        '--allow-unauthenticated',
        '--project', 'test',
        '--set-env-vars', 'FLASK_ENV=production',
        '--service-account', '1094025365695-compute@developer.gserviceaccount.com'
      ]

options:
  logging: CLOUD_LOGGING_ONLY
serviceAccount: '1094025365695-compute@developer.gserviceaccount.com'
