steps:
  - id: 'Build Application'
    name: 'gcr.io/cloud-builders/python'
    entrypoint: 'bash'
    args: ['-c', 'pip install -r requirements.txt']

  - id: 'Build Docker Image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag', 'us-east1-docker.pkg.dev/my-project/dev-app-artifact-registry/flask-app:$COMMIT_SHA', '-f', './deploy/dockerfile', './']

  - id: 'Push Docker Image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east1-docker.pkg.dev/my-project/dev-app-artifact-registry/flask-app:$COMMIT_SHA']

  - id: 'Deploy to Cloud Run'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'flask-app-service',
        '--image', 'us-east1-docker.pkg.dev/my-project/dev-app-artifact-registry/flask-app:$COMMIT_SHA',
        '--port', '3333',
        '--platform', 'managed',
        '--region', 'us-east1',
        '--allow-unauthenticated',
        '--project', 'my-project',
        '--set-env-vars','FLASK_ENV=production',
        '--service-account', 'my-service-account@my-project.iam.gserviceaccount.com'
      ]

options:
  logging: CLOUD_LOGGING_ONLY
serviceAccount: '1094025365695-compute@developer.gserviceaccount.com'